apiVersion: v1
kind: Pod
metadata:
  name: biomaj-consul
  labels:
      app: biomaj-consul
spec:
  hostname: consulnode1
  containers:
  - name: biomaj-consul
    image: hashicorp/consul:1.17
    command: ["consul"]
    args: ["agent", "-dev", "-client", "0.0.0.0", "-log-level", "info"]
