sudo: required

services:
  - docker

before_install:
  - echo "BIOMAJ_DIR=$(pwd)" > .env
  - echo "BIOMAJ_DATA_DIR=$(pwd)/biomaj" >> .env
  - mkdir -p biomaj biomaj/conf biomaj/log biomaj/lock biomaj/db biomaj/process biomaj/cache
  - cp test-local/etc/biomaj/conf.d/alu.properties biomaj/conf/
  - cp test-local/etc/biomaj/conf.d/local.properties biomaj/conf/

script:
  - docker run --rm -i hadolint/hadolint < Dockerfile || true
  - docker-compose config --q
  - docker build -t quay.io/osallou/biomaj .
  - docker-compose up -d
  - sleep 20
  - ./docker-test.sh local
  - docker-compose down
